name: loc

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  loc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Rust
        run: |
          rustup update stable --no-self-update && rustup default stable
      
      - name: Install tokeit
        run: |
          cargo +stable install tokeit --version 0.1.3 --locked
      
      - name: Count total lines of code
        run: |
          tokeit
      - name: Upload total loc to GitHub Gist
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b # v9
        with:
          github-token: ${{ secrets.GIST_PAT }}
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('tokeit.json', 'utf8');
            const gistId = '327b2a8aef9003246e45c6e47fe63937';
            await github.rest.gists.update({
              gist_id: gistId,
              files: {
                "iprobe": {
                  content: output
                }
              }
            });
